Loading pytorch-gpu/py3/1.6.0
  Loading requirement: gcc/8.3.1 cuda/10.2 nccl/2.6.4-1-cuda
    cudnn/7.6.5.32-cuda-10.2 intel-mkl/2020.1 magma/2.5.3-cuda
    openmpi/4.0.2-cuda
++ sed -n 2p parameters_combinations/mnist_classifier_ratio.txt
+ LINE='--gpu_devices 0 --max_iter 100 --batch_size 32 --lr 1e-2 --use_scheduler True --use_VAE True --is_VAE_var True --z_var_size 5 --lambda_BCE 1 --beta 1 --var_second_cnn_block True --var_third_cnn_block False --exp_name mnist_vae_var_kaggle_scheduler_1'
+ echo --gpu_devices 0 --max_iter 100 --batch_size 32 --lr 1e-2 --use_scheduler True --use_VAE True --is_VAE_var True --z_var_size 5 --lambda_BCE 1 --beta 1 --var_second_cnn_block True --var_third_cnn_block False --exp_name mnist_vae_var_kaggle_scheduler_1
+ python3 -u main.py --gpu_devices 0 --max_iter 100 --batch_size 32 --lr 1e-2 --use_scheduler True --use_VAE True --is_VAE_var True --z_var_size 5 --lambda_BCE 1 --beta 1 --var_second_cnn_block True --var_third_cnn_block False --exp_name mnist_vae_var_kaggle_scheduler_1
--- Logging error ---
Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'asc_time'
Call stack:
  File "main.py", line 307, in <module>
    main(args)
  File "main.py", line 31, in main
    net = SolverClassifier(arguments)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 342, in __init__
    self.test_loader_size))
Message: 'Dataset mnist: train with 60000 samples and 10000 test samples'
Arguments: ()
  0%|          | 0/100.0 [00:00<?, ?it/s]  2%|▏         | 2/100.0 [00:01<00:57,  1.70it/s] 14%|█▍        | 14/100.0 [00:01<00:35,  2.41it/s] 26%|██▌       | 26/100.0 [00:01<00:21,  3.41it/s] 38%|███▊      | 38/100.0 [00:01<00:12,  4.81it/s] 50%|█████     | 50/100.0 [00:01<00:07,  6.75it/s] 62%|██████▏   | 62/100.0 [00:01<00:04,  9.40it/s] 74%|███████▍  | 74/100.0 [00:01<00:02, 12.96it/s] 86%|████████▌ | 86/100.0 [00:01<00:00, 17.63it/s] 98%|█████████▊| 98/100.0 [00:02<00:00, 23.60it/s]110it [00:02, 30.91it/s]                          122it [00:02, 39.49it/s]134it [00:02, 49.00it/s]146it [00:02, 58.92it/s]158it [00:02, 68.65it/s]170it [00:02, 77.64it/s]182it [00:02, 85.50it/s]194it [00:02, 91.99it/s]206it [00:03, 97.18it/s]218it [00:03, 101.08it/s]230it [00:03, 104.04it/s]242it [00:03, 106.30it/s]254it [00:03, 107.89it/s]266it [00:03, 109.04it/s]278it [00:03, 109.75it/s]290it [00:03, 110.32it/s]302it [00:03, 110.56it/s]314it [00:03, 110.91it/s]326it [00:04, 111.17it/s]338it [00:04, 111.37it/s]350it [00:04, 111.53it/s]362it [00:04, 111.65it/s]374it [00:04, 111.70it/s]386it [00:04, 111.68it/s]398it [00:04, 111.66it/s]410it [00:04, 111.72it/s]422it [00:04, 111.74it/s]434it [00:05, 111.79it/s]446it [00:05, 111.79it/s]458it [00:05, 111.77it/s]470it [00:05, 111.79it/s]482it [00:05, 111.81it/s]494it [00:05, 111.83it/s]506it [00:05, 111.78it/s]518it [00:05, 111.81it/s]530it [00:05, 111.74it/s]542it [00:06, 111.74it/s]554it [00:06, 111.79it/s]566it [00:06, 111.79it/s]578it [00:06, 111.74it/s]590it [00:06, 111.76it/s]602it [00:06, 110.90it/s]614it [00:06, 111.12it/s]626it [00:06, 111.34it/s]638it [00:06, 111.48it/s]650it [00:06, 111.58it/s]662it [00:07, 111.65it/s]674it [00:07, 111.70it/s]686it [00:07, 111.72it/s]698it [00:07, 111.78it/s]710it [00:07, 111.82it/s]722it [00:07, 111.78it/s]734it [00:07, 111.75it/s]746it [00:07, 111.76it/s]758it [00:07, 111.76it/s]770it [00:08, 111.78it/s]782it [00:08, 111.84it/s]794it [00:08, 111.89it/s]806it [00:08, 111.88it/s]818it [00:08, 111.89it/s]830it [00:08, 111.90it/s]842it [00:08, 111.74it/s]854it [00:08, 111.71it/s]866it [00:08, 111.75it/s]878it [00:09, 111.75it/s]890it [00:09, 111.76it/s]902it [00:09, 111.75it/s]914it [00:09, 111.73it/s]926it [00:09, 111.78it/s]938it [00:09, 111.86it/s]950it [00:09, 111.80it/s]962it [00:09, 98.09it/s] 974it [00:09, 101.86it/s]986it [00:10, 104.59it/s]998it [00:10, 106.69it/s]1010it [00:10, 108.16it/s]1022it [00:10, 109.25it/s]1034it [00:10, 110.05it/s]1046it [00:10, 110.61it/s]1058it [00:10, 110.96it/s]1070it [00:10, 111.17it/s]1082it [00:10, 111.38it/s]1094it [00:11, 111.54it/s]1106it [00:11, 111.60it/s]1118it [00:11, 111.68it/s]1130it [00:11, 111.74it/s]1142it [00:11, 111.63it/s]1154it [00:11, 111.71it/s]1166it [00:11, 111.75it/s]1178it [00:11, 111.78it/s]1190it [00:11, 111.76it/s]/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [5,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [7,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [14,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [16,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [17,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [18,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [19,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [21,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [22,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [23,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [24,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [25,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/gpfs7kro/gpfslocalsup/src/pub/anaconda-py3/2020.02/pytorch-1.6.0/pytorch-1.6/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [56,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    main(args)
  File "main.py", line 34, in main
    net.train()
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 665, in train
    data = data.to(self.device)  # Variable(data.to(self.device))
RuntimeError: CUDA error: device-side assert triggered
1200it [00:12, 99.99it/s] 
+ wait
+ echo 'All done !'
