Loading pytorch-gpu/py3/1.6.0
  Loading requirement: gcc/8.3.1 cuda/10.2 nccl/2.6.4-1-cuda
    cudnn/7.6.5.32-cuda-10.2 intel-mkl/2020.1 magma/2.5.3-cuda
    openmpi/4.0.2-cuda
+ python3 -u run_resutls.py
Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/numpy/lib/npyio.py", line 460, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_resutls.py", line 758, in <module>
    is_encoder_struct=False)
  File "run_resutls.py", line 165, in run_exp_extraction_and_visualization_custom_BK
    ES_reconstruction)
  File "run_resutls.py", line 273, in run_VAE
    same_binary_code(net, model_name, loader, nb_class, train_test=train_test, save=True, Hmg_dist=False, is_VAE=True)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/visualizer_CNN.py", line 3007, in same_binary_code
    uniq_code = np.load(path_model_uniq_code, allow_pickle=True)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'binary_encoder_struct_results/uniq_code/mnist_VAE_s10_v5_BF_test.npy' as a pickle
+ wait
+ echo 'All done !'
