--- Logging error ---
Traceback (most recent call last):
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'asc_time'
Call stack:
  File "main.py", line 222, in <module>
    main(args)
  File "main.py", line 30, in main
    net = SolverClassifier(arguments)
  File "/data1/data/expes/julien.dejasmin/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 219, in __init__
    self.test_loader_size))
Message: 'Train mnist with 60000 train samples, 0 valid samples and 10000 test samples'
Arguments: ()
  0%|          | 0/50.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 222, in <module>
    main(args)
  File "main.py", line 33, in main
    net.train()
  File "/data1/data/expes/julien.dejasmin/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 397, in train
    other_ratio=self.other_ratio)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/data/expes/julien.dejasmin/Thesis/Pytorch_vanilla_Beta_VAE/models/custom_CNN_BK.py", line 216, in forward
    ratio = self.compute_ratio_batch(z_struct, labels, nb_class, other_ratio=other_ratio)
  File "/data1/data/expes/julien.dejasmin/Thesis/Pytorch_vanilla_Beta_VAE/models/custom_CNN_BK.py", line 242, in compute_ratio_batch
    variance_intra_class = torch.square(std_class)  # shape: (nb_class, len(z_struct))
AttributeError: module 'torch' has no attribute 'square'
  2%|‚ñè         | 1/50.0 [00:01<01:04,  1.31s/it]
